using System.Globalization;
using CommunityToolkit.Mvvm.ComponentModel;

namespace AudioSwitcher.Services;

public sealed record LanguageOption(string Code, string NativeName)
{
    public override string ToString() => NativeName;
}

public sealed class LocalizationService : ObservableObject
{
    private const string DefaultLanguage = "en";

    private static readonly IReadOnlyList<LanguageOption> Languages =
    [
        new("en", "English"),
        new("ru", "Русский"),
        new("uk", "Українська"),
        new("fr", "Français"),
        new("it", "Italiano"),
        new("pl", "Polski"),
    ];

    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Translations =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["en"] = new Dictionary<string, string>
            {
                ["WindowsAudioRouting"] = "WINDOWS AUDIO ROUTING",
                ["RefreshDevices"] = "Refresh devices",
                ["RefreshDevicesTip"] = "Reload available Windows audio devices",
                ["Settings"] = "Settings",
                ["About"] = "About",
                ["AboutDescription"] = "Windows audio profiles and global shortcuts. Made by Diddlik.",
                ["CheckForUpdates"] = "Check for updates",
                ["PackageCredits"] = "Package credits",
                ["PackageCreditsHint"] = "Thanks to the authors of these direct and transitive dependencies, including development tools. Package links include license details.",
                ["StandaloneUpdates"] = "Automatic updates require the installed version. For this standalone build, download a release from GitHub.",
                ["ReleaseNotes"] = "Releases and changelog",
                ["SourceCode"] = "Source code",
                ["Close"] = "Close",
                ["System"] = "SYSTEM",
                ["Language"] = "Language",
                ["StartWithWindows"] = "Start with Windows",
                ["CloseHint"] = "Closing hides the window. Use the tray menu to exit.",
                ["Save"] = "Save",
                ["UnsavedChanges"] = "Unsaved changes",
                ["Profiles"] = "Profiles",
                ["NoProfileSelected"] = "No profile selected",
                ["NoProfileSelectedHint"] = "Add a profile to pair an output device with an input device.",
                ["AddProfile"] = "Add profile",
                ["RemoveProfile"] = "Remove profile",
                ["Profile"] = "PROFILE",
                ["DeviceCombination"] = "Device combination",
                ["ActivateNow"] = "Activate now",
                ["ActivateHelp"] = "Sets both devices as the Windows default for playback, recording and communications.",
                ["ActivatedAt"] = "Activated at {0}",
                ["NotActivatedThisSession"] = "Not activated in this session",
                ["DeviceNotAvailable"] = "Device not available",
                ["Name"] = "Profile name",
                ["NameExample"] = "e.g. Headset",
                ["ProfileName"] = "Profile name",
                ["Output"] = "Output device",
                ["Input"] = "Input device",
                ["OutputDevice"] = "Output device",
                ["InputDevice"] = "Input device",
                ["ProfileShortcutLabel"] = "Global shortcut for this profile",
                ["ShortcutWatermark"] = "Click here and press a shortcut",
                ["ProfileShortcut"] = "Profile shortcut",
                ["ShortcutHelp"] = "Focus the field and press a key combination. Delete or Backspace clears it.",
                ["ShortcutHint"] = "Click, press a combination · Delete or Backspace clears it",
                ["QuickSwitch"] = "Quick switch",
                ["QuickSwitchTitle"] = "One shortcut switches between two profiles. AudioSwitcher checks the current default output device and activates the other profile.",
                ["FirstToggleProfile"] = "First switch profile",
                ["SecondToggleProfile"] = "Second switch profile",
                ["ToggleShortcut"] = "Switch shortcut",
                ["LanguageHelp"] = "The interface changes immediately. Save to keep the choice.",
                ["StartupHelp"] = "Opens in the system tray when you sign in. No administrator rights required.",
                ["TrayTitle"] = "Closing the window",
                ["TrayBody"] = "Closing the window keeps AudioSwitcher running in the system tray, so shortcuts and updates keep working. To quit, right-click the tray icon and choose Exit.",
                ["Updates"] = "Updates",
                ["UpdatesBody"] = "Stable updates download automatically and install after you exit AudioSwitcher.",
                ["Ready"] = "Ready",
                ["Version"] = "Version {0}",
                ["Unknown"] = "unknown",
                ["DefaultProfile"] = "Profile {0}",
                ["ProfileCreated"] = "New profile created.",
                ["ProfileRemoved"] = "Profile removed. Save to apply the change.",
                ["DeviceCounts"] = "{0} outputs · {1} inputs",
                ["ConfigurationSaved"] = "Configuration saved.",
                ["SaveFailed"] = "Save failed: {0}",
                ["SelectTwoProfiles"] = "Select two profiles for switching.",
                ["UnavailableDevice"] = "“{0}” refers to an unavailable device.",
                ["ProfileActive"] = "{0} is active.",
                ["ProfileActivationFailed"] = "Profile could not be activated: {0}",
                ["ProfileRequired"] = "At least one profile is required.",
                ["ProfileNameRequired"] = "Every profile needs a name.",
                ["UniqueProfileNames"] = "Profile names must be unique.",
                ["ProfileDevicesRequired"] = "“{0}” needs an input and output device.",
                ["UniqueShortcuts"] = "Shortcuts cannot be assigned more than once.",
                ["ToggleProfilesRequired"] = "The switch shortcut needs two different profiles.",
                ["ShortcutMissing"] = "Shortcut is missing.",
                ["InvalidKey"] = "Invalid key: {0}.",
                ["ShortcutKeyRequired"] = "Shortcut needs a key.",
                ["ShortcutModifierRequired"] = "Shortcut needs Ctrl, Alt, Shift, or Win.",
                ["ShortcutCombinationRequired"] = "Shortcut needs Ctrl, Alt, Shift, or Win plus a key.",
                ["ShortcutRegistrationTimeout"] = "Shortcut registration did not respond.",
                ["ShortcutAlreadyInUse"] = "Shortcut {0} is already in use.",
                ["Open"] = "Open",
                ["Exit"] = "Exit",
                ["UpdatePreparingFailed"] = "Update could not be prepared: {0}",
                ["UpdateCheckFailed"] = "Update check failed: {0}",
                ["CheckingUpdates"] = "Checking for updates…",
                ["UpToDate"] = "AudioSwitcher is up to date.",
                ["DownloadingUpdate"] = "Downloading update {0}…",
                ["DownloadProgress"] = "Downloading update: {0}%",
                ["UpdateOnExit"] = "Update {0} will be installed on exit.",
                ["ProfileActivatedOverlay"] = "✓  Profile “{0}” activated",
            },
            ["ru"] = new Dictionary<string, string>
            {
                ["WindowsAudioRouting"] = "МАРШРУТИЗАЦИЯ ЗВУКА WINDOWS",
                ["RefreshDevices"] = "Обновить устройства",
                ["RefreshDevicesTip"] = "Повторно загрузить доступные аудиоустройства Windows",
                ["Settings"] = "Настройки",
                ["About"] = "О программе",
                ["AboutDescription"] = "Аудиопрофили Windows и глобальные сочетания клавиш. Автор: Diddlik.",
                ["CheckForUpdates"] = "Проверить обновления",
                ["PackageCredits"] = "Используемые пакеты",
                ["PackageCreditsHint"] = "Спасибо авторам прямых и транзитивных зависимостей, включая средства разработки. Информация о лицензиях доступна по ссылкам на пакеты.",
                ["StandaloneUpdates"] = "Автообновления доступны в установленной версии. Для этой переносной сборки скачайте выпуск с GitHub.",
                ["ReleaseNotes"] = "Выпуски и изменения",
                ["SourceCode"] = "Исходный код",
                ["Close"] = "Закрыть",
                ["System"] = "СИСТЕМА",
                ["Language"] = "Язык",
                ["StartWithWindows"] = "Запускать вместе с Windows",
                ["CloseHint"] = "При закрытии окно скрывается. Для выхода используйте меню в области уведомлений.",
                ["Save"] = "Сохранить",
                ["UnsavedChanges"] = "Несохранённые изменения",
                ["Profiles"] = "Профили",
                ["NoProfileSelected"] = "Профиль не выбран",
                ["NoProfileSelectedHint"] = "Добавьте профиль, чтобы связать устройство вывода с устройством ввода.",
                ["AddProfile"] = "Добавить профиль",
                ["RemoveProfile"] = "Удалить профиль",
                ["Profile"] = "ПРОФИЛЬ",
                ["DeviceCombination"] = "Комбинация устройств",
                ["ActivateNow"] = "Активировать",
                ["ActivateHelp"] = "Назначает оба устройства устройствами Windows по умолчанию для воспроизведения, записи и связи.",
                ["ActivatedAt"] = "Активирован в {0}",
                ["NotActivatedThisSession"] = "Не активировался в этом сеансе",
                ["DeviceNotAvailable"] = "Устройство недоступно",
                ["Name"] = "Название профиля",
                ["NameExample"] = "например, Гарнитура",
                ["ProfileName"] = "Имя профиля",
                ["Output"] = "Устройство вывода",
                ["Input"] = "Устройство ввода",
                ["OutputDevice"] = "Устройство вывода",
                ["InputDevice"] = "Устройство ввода",
                ["ProfileShortcutLabel"] = "Глобальное сочетание клавиш для профиля",
                ["ShortcutWatermark"] = "Нажмите здесь и введите сочетание",
                ["ProfileShortcut"] = "Сочетание профиля",
                ["ShortcutHelp"] = "Установите фокус и нажмите сочетание клавиш. Delete или Backspace очищает поле.",
                ["ShortcutHint"] = "Щёлкните и нажмите сочетание · Delete или Backspace очищает поле",
                ["QuickSwitch"] = "Быстрое переключение",
                ["QuickSwitchTitle"] = "Одно сочетание клавиш переключает два профиля. AudioSwitcher проверяет текущее устройство вывода по умолчанию и активирует другой профиль.",
                ["FirstToggleProfile"] = "Первый профиль",
                ["SecondToggleProfile"] = "Второй профиль",
                ["ToggleShortcut"] = "Сочетание для переключения",
                ["LanguageHelp"] = "Интерфейс меняется сразу. Нажмите «Сохранить», чтобы запомнить выбор.",
                ["StartupHelp"] = "Открывается в области уведомлений при входе в систему. Права администратора не нужны.",
                ["TrayTitle"] = "Закрытие окна",
                ["TrayBody"] = "После закрытия окна AudioSwitcher продолжает работать в области уведомлений, поэтому сочетания клавиш и обновления остаются активными. Чтобы выйти, щёлкните значок правой кнопкой мыши и выберите «Выход».",
                ["Updates"] = "Обновления",
                ["UpdatesBody"] = "Стабильные обновления загружаются автоматически и устанавливаются после выхода из AudioSwitcher.",
                ["Ready"] = "Готово",
                ["Version"] = "Версия {0}",
                ["Unknown"] = "неизвестно",
                ["DefaultProfile"] = "Профиль {0}",
                ["ProfileCreated"] = "Новый профиль создан.",
                ["ProfileRemoved"] = "Профиль удалён. Сохраните изменения.",
                ["DeviceCounts"] = "Выходов: {0} · входов: {1}",
                ["ConfigurationSaved"] = "Конфигурация сохранена.",
                ["SaveFailed"] = "Не удалось сохранить: {0}",
                ["SelectTwoProfiles"] = "Выберите два профиля для переключения.",
                ["UnavailableDevice"] = "«{0}» ссылается на недоступное устройство.",
                ["ProfileActive"] = "Профиль {0} активен.",
                ["ProfileActivationFailed"] = "Не удалось активировать профиль: {0}",
                ["ProfileRequired"] = "Требуется хотя бы один профиль.",
                ["ProfileNameRequired"] = "Каждому профилю нужно имя.",
                ["UniqueProfileNames"] = "Имена профилей должны быть уникальными.",
                ["ProfileDevicesRequired"] = "Для «{0}» нужны устройства ввода и вывода.",
                ["UniqueShortcuts"] = "Сочетания клавиш не должны повторяться.",
                ["ToggleProfilesRequired"] = "Для переключения нужны два разных профиля.",
                ["ShortcutMissing"] = "Сочетание клавиш не указано.",
                ["InvalidKey"] = "Недопустимая клавиша: {0}.",
                ["ShortcutKeyRequired"] = "Сочетание должно содержать клавишу.",
                ["ShortcutModifierRequired"] = "Сочетание должно содержать Ctrl, Alt, Shift или Win.",
                ["ShortcutCombinationRequired"] = "Сочетание должно содержать Ctrl, Alt, Shift или Win и клавишу.",
                ["ShortcutRegistrationTimeout"] = "Регистрация сочетаний клавиш не ответила.",
                ["ShortcutAlreadyInUse"] = "Сочетание {0} уже используется.",
                ["Open"] = "Открыть",
                ["Exit"] = "Выйти",
                ["UpdatePreparingFailed"] = "Не удалось подготовить обновление: {0}",
                ["UpdateCheckFailed"] = "Не удалось проверить обновления: {0}",
                ["CheckingUpdates"] = "Проверка обновлений…",
                ["UpToDate"] = "Установлена последняя версия AudioSwitcher.",
                ["DownloadingUpdate"] = "Загрузка обновления {0}…",
                ["DownloadProgress"] = "Загрузка обновления: {0}%",
                ["UpdateOnExit"] = "Обновление {0} будет установлено при выходе.",
                ["ProfileActivatedOverlay"] = "✓  Профиль «{0}» активирован",
            },
            ["uk"] = new Dictionary<string, string>
            {
                ["WindowsAudioRouting"] = "МАРШРУТИЗАЦІЯ ЗВУКУ WINDOWS",
                ["RefreshDevices"] = "Оновити пристрої",
                ["RefreshDevicesTip"] = "Повторно завантажити доступні аудіопристрої Windows",
                ["Settings"] = "Налаштування",
                ["About"] = "Про програму",
                ["AboutDescription"] = "Аудіопрофілі Windows і глобальні сполучення клавіш. Автор: Diddlik.",
                ["CheckForUpdates"] = "Перевірити оновлення",
                ["PackageCredits"] = "Використані пакети",
                ["PackageCreditsHint"] = "Дякуємо авторам прямих і транзитивних залежностей, зокрема засобів розробки. Відомості про ліцензії доступні за посиланнями на пакети.",
                ["StandaloneUpdates"] = "Автооновлення доступні у встановленій версії. Для цієї переносної збірки завантажте випуск із GitHub.",
                ["ReleaseNotes"] = "Випуски та зміни",
                ["SourceCode"] = "Вихідний код",
                ["Close"] = "Закрити",
                ["System"] = "СИСТЕМА",
                ["Language"] = "Мова",
                ["StartWithWindows"] = "Запускати разом із Windows",
                ["CloseHint"] = "Після закриття вікно ховається. Для виходу скористайтеся меню в області сповіщень.",
                ["Save"] = "Зберегти",
                ["UnsavedChanges"] = "Незбережені зміни",
                ["Profiles"] = "Профілі",
                ["NoProfileSelected"] = "Профіль не вибрано",
                ["NoProfileSelectedHint"] = "Додайте профіль, щоб поєднати пристрій виведення з пристроєм введення.",
                ["AddProfile"] = "Додати профіль",
                ["RemoveProfile"] = "Видалити профіль",
                ["Profile"] = "ПРОФІЛЬ",
                ["DeviceCombination"] = "Комбінація пристроїв",
                ["ActivateNow"] = "Активувати",
                ["ActivateHelp"] = "Робить обидва пристрої типовими в Windows для відтворення, запису та зв’язку.",
                ["ActivatedAt"] = "Активовано о {0}",
                ["NotActivatedThisSession"] = "Не активувався в цьому сеансі",
                ["DeviceNotAvailable"] = "Пристрій недоступний",
                ["Name"] = "Назва профілю",
                ["NameExample"] = "наприклад, Гарнітура",
                ["ProfileName"] = "Назва профілю",
                ["Output"] = "Пристрій виведення",
                ["Input"] = "Пристрій введення",
                ["OutputDevice"] = "Пристрій виводу",
                ["InputDevice"] = "Пристрій вводу",
                ["ProfileShortcutLabel"] = "Глобальне сполучення клавіш для профілю",
                ["ShortcutWatermark"] = "Натисніть тут і введіть сполучення",
                ["ProfileShortcut"] = "Сполучення профілю",
                ["ShortcutHelp"] = "Установіть фокус і натисніть сполучення клавіш. Delete або Backspace очищає поле.",
                ["ShortcutHint"] = "Клацніть і натисніть сполучення · Delete або Backspace очищає поле",
                ["QuickSwitch"] = "Швидке перемикання",
                ["QuickSwitchTitle"] = "Одне сполучення клавіш перемикає між двома профілями. AudioSwitcher перевіряє поточний типовий пристрій виведення й активує інший профіль.",
                ["FirstToggleProfile"] = "Перший профіль",
                ["SecondToggleProfile"] = "Другий профіль",
                ["ToggleShortcut"] = "Сполучення для перемикання",
                ["LanguageHelp"] = "Інтерфейс змінюється одразу. Натисніть «Зберегти», щоб запам’ятати вибір.",
                ["StartupHelp"] = "Відкривається в області сповіщень під час входу. Права адміністратора не потрібні.",
                ["TrayTitle"] = "Закриття вікна",
                ["TrayBody"] = "Після закриття вікна AudioSwitcher працює в області сповіщень, тож сполучення клавіш і оновлення лишаються активними. Щоб вийти, клацніть значок правою кнопкою й виберіть «Вихід».",
                ["Updates"] = "Оновлення",
                ["UpdatesBody"] = "Стабільні оновлення завантажуються автоматично й встановлюються після виходу з AudioSwitcher.",
                ["Ready"] = "Готово",
                ["Version"] = "Версія {0}",
                ["Unknown"] = "невідомо",
                ["DefaultProfile"] = "Профіль {0}",
                ["ProfileCreated"] = "Новий профіль створено.",
                ["ProfileRemoved"] = "Профіль видалено. Збережіть зміни.",
                ["DeviceCounts"] = "Виходів: {0} · входів: {1}",
                ["ConfigurationSaved"] = "Конфігурацію збережено.",
                ["SaveFailed"] = "Не вдалося зберегти: {0}",
                ["SelectTwoProfiles"] = "Виберіть два профілі для перемикання.",
                ["UnavailableDevice"] = "«{0}» посилається на недоступний пристрій.",
                ["ProfileActive"] = "Профіль {0} активний.",
                ["ProfileActivationFailed"] = "Не вдалося активувати профіль: {0}",
                ["ProfileRequired"] = "Потрібен принаймні один профіль.",
                ["ProfileNameRequired"] = "Кожному профілю потрібна назва.",
                ["UniqueProfileNames"] = "Назви профілів мають бути унікальними.",
                ["ProfileDevicesRequired"] = "Для «{0}» потрібні пристрої вводу та виводу.",
                ["UniqueShortcuts"] = "Сполучення клавіш не можуть повторюватися.",
                ["ToggleProfilesRequired"] = "Для перемикання потрібні два різні профілі.",
                ["ShortcutMissing"] = "Сполучення клавіш не вказано.",
                ["InvalidKey"] = "Неприпустима клавіша: {0}.",
                ["ShortcutKeyRequired"] = "Сполучення має містити клавішу.",
                ["ShortcutModifierRequired"] = "Сполучення має містити Ctrl, Alt, Shift або Win.",
                ["ShortcutCombinationRequired"] = "Сполучення має містити Ctrl, Alt, Shift або Win і клавішу.",
                ["ShortcutRegistrationTimeout"] = "Реєстрація сполучень клавіш не відповіла.",
                ["ShortcutAlreadyInUse"] = "Сполучення {0} вже використовується.",
                ["Open"] = "Відкрити",
                ["Exit"] = "Вийти",
                ["UpdatePreparingFailed"] = "Не вдалося підготувати оновлення: {0}",
                ["UpdateCheckFailed"] = "Не вдалося перевірити оновлення: {0}",
                ["CheckingUpdates"] = "Перевірка оновлень…",
                ["UpToDate"] = "Установлено останню версію AudioSwitcher.",
                ["DownloadingUpdate"] = "Завантаження оновлення {0}…",
                ["DownloadProgress"] = "Завантаження оновлення: {0}%",
                ["UpdateOnExit"] = "Оновлення {0} буде встановлено під час виходу.",
                ["ProfileActivatedOverlay"] = "✓  Профіль «{0}» активовано",
            },
            ["fr"] = new Dictionary<string, string>
            {
                ["WindowsAudioRouting"] = "ROUTAGE AUDIO WINDOWS",
                ["RefreshDevices"] = "Actualiser les périphériques",
                ["RefreshDevicesTip"] = "Recharger les périphériques audio Windows disponibles",
                ["Settings"] = "Paramètres",
                ["About"] = "À propos",
                ["AboutDescription"] = "Profils audio Windows et raccourcis globaux. Créé par Diddlik.",
                ["CheckForUpdates"] = "Rechercher des mises à jour",
                ["PackageCredits"] = "Crédits des packages",
                ["PackageCreditsHint"] = "Merci aux auteurs des dépendances directes et transitives, y compris les outils de développement. Les liens des packages donnent accès aux licences.",
                ["StandaloneUpdates"] = "Les mises à jour automatiques nécessitent la version installée. Pour cette version autonome, téléchargez une version sur GitHub.",
                ["ReleaseNotes"] = "Versions et modifications",
                ["SourceCode"] = "Code source",
                ["Close"] = "Fermer",
                ["System"] = "SYSTÈME",
                ["Language"] = "Langue",
                ["StartWithWindows"] = "Démarrer avec Windows",
                ["CloseHint"] = "La fermeture masque la fenêtre. Utilisez le menu de la zone de notification pour quitter.",
                ["Save"] = "Enregistrer",
                ["UnsavedChanges"] = "Modifications non enregistrées",
                ["Profiles"] = "Profils",
                ["NoProfileSelected"] = "Aucun profil sélectionné",
                ["NoProfileSelectedHint"] = "Ajoutez un profil pour associer un périphérique de sortie à un périphérique d’entrée.",
                ["AddProfile"] = "Ajouter un profil",
                ["RemoveProfile"] = "Supprimer le profil",
                ["Profile"] = "PROFIL",
                ["DeviceCombination"] = "Combinaison de périphériques",
                ["ActivateNow"] = "Activer maintenant",
                ["ActivateHelp"] = "Définit les deux périphériques par défaut dans Windows pour la lecture, l’enregistrement et les communications.",
                ["ActivatedAt"] = "Activé à {0}",
                ["NotActivatedThisSession"] = "Pas encore activé dans cette session",
                ["DeviceNotAvailable"] = "Périphérique indisponible",
                ["Name"] = "Nom du profil",
                ["NameExample"] = "p. ex. Casque",
                ["ProfileName"] = "Nom du profil",
                ["Output"] = "Périphérique de sortie",
                ["Input"] = "Périphérique d’entrée",
                ["OutputDevice"] = "Périphérique de sortie",
                ["InputDevice"] = "Périphérique d’entrée",
                ["ProfileShortcutLabel"] = "Raccourci global de ce profil",
                ["ShortcutWatermark"] = "Cliquez ici et appuyez sur un raccourci",
                ["ProfileShortcut"] = "Raccourci du profil",
                ["ShortcutHelp"] = "Placez le focus dans le champ et appuyez sur une combinaison. Suppr ou Retour arrière l’efface.",
                ["ShortcutHint"] = "Cliquez et appuyez sur une combinaison · Suppr ou Retour arrière l’efface",
                ["QuickSwitch"] = "Bascule rapide",
                ["QuickSwitchTitle"] = "Un seul raccourci bascule entre deux profils. AudioSwitcher vérifie le périphérique de sortie par défaut actuel et active l’autre profil.",
                ["FirstToggleProfile"] = "Premier profil",
                ["SecondToggleProfile"] = "Deuxième profil",
                ["ToggleShortcut"] = "Raccourci de bascule",
                ["LanguageHelp"] = "L’interface change immédiatement. Enregistrez pour conserver ce choix.",
                ["StartupHelp"] = "S’ouvre dans la zone de notification à l’ouverture de session. Aucun droit administrateur requis.",
                ["TrayTitle"] = "Fermeture de la fenêtre",
                ["TrayBody"] = "Fermer la fenêtre laisse AudioSwitcher actif dans la zone de notification : les raccourcis et les mises à jour continuent de fonctionner. Pour quitter, faites un clic droit sur l’icône et choisissez Quitter.",
                ["Updates"] = "Mises à jour",
                ["UpdatesBody"] = "Les mises à jour stables se téléchargent automatiquement et s’installent après la fermeture d’AudioSwitcher.",
                ["Ready"] = "Prêt",
                ["Version"] = "Version {0}",
                ["Unknown"] = "inconnue",
                ["DefaultProfile"] = "Profil {0}",
                ["ProfileCreated"] = "Nouveau profil créé.",
                ["ProfileRemoved"] = "Profil supprimé. Enregistrez pour appliquer la modification.",
                ["DeviceCounts"] = "{0} sorties · {1} entrées",
                ["ConfigurationSaved"] = "Configuration enregistrée.",
                ["SaveFailed"] = "Échec de l’enregistrement : {0}",
                ["SelectTwoProfiles"] = "Sélectionnez deux profils pour la bascule.",
                ["UnavailableDevice"] = "« {0} » fait référence à un périphérique indisponible.",
                ["ProfileActive"] = "{0} est actif.",
                ["ProfileActivationFailed"] = "Impossible d’activer le profil : {0}",
                ["ProfileRequired"] = "Au moins un profil est requis.",
                ["ProfileNameRequired"] = "Chaque profil doit avoir un nom.",
                ["UniqueProfileNames"] = "Les noms de profils doivent être uniques.",
                ["ProfileDevicesRequired"] = "« {0} » nécessite un périphérique d’entrée et de sortie.",
                ["UniqueShortcuts"] = "Un raccourci ne peut pas être attribué plusieurs fois.",
                ["ToggleProfilesRequired"] = "Le raccourci de bascule nécessite deux profils différents.",
                ["ShortcutMissing"] = "Le raccourci est manquant.",
                ["InvalidKey"] = "Touche non valide : {0}.",
                ["ShortcutKeyRequired"] = "Le raccourci nécessite une touche.",
                ["ShortcutModifierRequired"] = "Le raccourci nécessite Ctrl, Alt, Maj ou Win.",
                ["ShortcutCombinationRequired"] = "Le raccourci nécessite Ctrl, Alt, Maj ou Win et une touche.",
                ["ShortcutRegistrationTimeout"] = "L’enregistrement des raccourcis n’a pas répondu.",
                ["ShortcutAlreadyInUse"] = "Le raccourci {0} est déjà utilisé.",
                ["Open"] = "Ouvrir",
                ["Exit"] = "Quitter",
                ["UpdatePreparingFailed"] = "Impossible de préparer la mise à jour : {0}",
                ["UpdateCheckFailed"] = "Échec de la recherche de mises à jour : {0}",
                ["CheckingUpdates"] = "Recherche de mises à jour…",
                ["UpToDate"] = "AudioSwitcher est à jour.",
                ["DownloadingUpdate"] = "Téléchargement de la mise à jour {0}…",
                ["DownloadProgress"] = "Téléchargement de la mise à jour : {0}%",
                ["UpdateOnExit"] = "La mise à jour {0} sera installée à la fermeture.",
                ["ProfileActivatedOverlay"] = "✓  Profil « {0} » activé",
            },
            ["it"] = new Dictionary<string, string>
            {
                ["WindowsAudioRouting"] = "INSTRADAMENTO AUDIO WINDOWS",
                ["RefreshDevices"] = "Aggiorna dispositivi",
                ["RefreshDevicesTip"] = "Ricarica i dispositivi audio Windows disponibili",
                ["Settings"] = "Impostazioni",
                ["About"] = "Informazioni",
                ["AboutDescription"] = "Profili audio Windows e scorciatoie globali. Creato da Diddlik.",
                ["CheckForUpdates"] = "Controlla aggiornamenti",
                ["PackageCredits"] = "Crediti dei pacchetti",
                ["PackageCreditsHint"] = "Grazie agli autori delle dipendenze dirette e transitive, inclusi gli strumenti di sviluppo. I link dei pacchetti riportano le licenze.",
                ["StandaloneUpdates"] = "Gli aggiornamenti automatici richiedono la versione installata. Per questa build autonoma, scarica una versione da GitHub.",
                ["ReleaseNotes"] = "Versioni e modifiche",
                ["SourceCode"] = "Codice sorgente",
                ["Close"] = "Chiudi",
                ["System"] = "SISTEMA",
                ["Language"] = "Lingua",
                ["StartWithWindows"] = "Avvia con Windows",
                ["CloseHint"] = "La chiusura nasconde la finestra. Usa il menu nell’area di notifica per uscire.",
                ["Save"] = "Salva",
                ["UnsavedChanges"] = "Modifiche non salvate",
                ["Profiles"] = "Profili",
                ["NoProfileSelected"] = "Nessun profilo selezionato",
                ["NoProfileSelectedHint"] = "Aggiungi un profilo per abbinare un dispositivo di uscita a uno di ingresso.",
                ["AddProfile"] = "Aggiungi profilo",
                ["RemoveProfile"] = "Rimuovi profilo",
                ["Profile"] = "PROFILO",
                ["DeviceCombination"] = "Combinazione di dispositivi",
                ["ActivateNow"] = "Attiva ora",
                ["ActivateHelp"] = "Imposta entrambi i dispositivi come predefiniti di Windows per riproduzione, registrazione e comunicazioni.",
                ["ActivatedAt"] = "Attivato alle {0}",
                ["NotActivatedThisSession"] = "Non attivato in questa sessione",
                ["DeviceNotAvailable"] = "Dispositivo non disponibile",
                ["Name"] = "Nome profilo",
                ["NameExample"] = "ad es. Cuffie",
                ["ProfileName"] = "Nome profilo",
                ["Output"] = "Dispositivo di uscita",
                ["Input"] = "Dispositivo di ingresso",
                ["OutputDevice"] = "Dispositivo di uscita",
                ["InputDevice"] = "Dispositivo di ingresso",
                ["ProfileShortcutLabel"] = "Scorciatoia globale per questo profilo",
                ["ShortcutWatermark"] = "Fai clic qui e premi una scorciatoia",
                ["ProfileShortcut"] = "Scorciatoia profilo",
                ["ShortcutHelp"] = "Attiva il campo e premi una combinazione. Canc o Backspace la elimina.",
                ["ShortcutHint"] = "Fai clic e premi una combinazione · Canc o Backspace la elimina",
                ["QuickSwitch"] = "Cambio rapido",
                ["QuickSwitchTitle"] = "Una sola scorciatoia alterna due profili. AudioSwitcher controlla il dispositivo di uscita predefinito attuale e attiva l’altro profilo.",
                ["FirstToggleProfile"] = "Primo profilo",
                ["SecondToggleProfile"] = "Secondo profilo",
                ["ToggleShortcut"] = "Scorciatoia di cambio",
                ["LanguageHelp"] = "L’interfaccia cambia subito. Salva per mantenere la scelta.",
                ["StartupHelp"] = "Si apre nell’area di notifica all’accesso. Non servono diritti di amministratore.",
                ["TrayTitle"] = "Chiusura della finestra",
                ["TrayBody"] = "Chiudendo la finestra AudioSwitcher resta attivo nell’area di notifica, così scorciatoie e aggiornamenti continuano a funzionare. Per uscire, fai clic destro sull’icona e scegli Esci.",
                ["Updates"] = "Aggiornamenti",
                ["UpdatesBody"] = "Gli aggiornamenti stabili vengono scaricati automaticamente e installati dopo la chiusura di AudioSwitcher.",
                ["Ready"] = "Pronto",
                ["Version"] = "Versione {0}",
                ["Unknown"] = "sconosciuta",
                ["DefaultProfile"] = "Profilo {0}",
                ["ProfileCreated"] = "Nuovo profilo creato.",
                ["ProfileRemoved"] = "Profilo rimosso. Salva per applicare la modifica.",
                ["DeviceCounts"] = "{0} uscite · {1} ingressi",
                ["ConfigurationSaved"] = "Configurazione salvata.",
                ["SaveFailed"] = "Salvataggio non riuscito: {0}",
                ["SelectTwoProfiles"] = "Seleziona due profili per il cambio.",
                ["UnavailableDevice"] = "“{0}” fa riferimento a un dispositivo non disponibile.",
                ["ProfileActive"] = "{0} è attivo.",
                ["ProfileActivationFailed"] = "Impossibile attivare il profilo: {0}",
                ["ProfileRequired"] = "È richiesto almeno un profilo.",
                ["ProfileNameRequired"] = "Ogni profilo deve avere un nome.",
                ["UniqueProfileNames"] = "I nomi dei profili devono essere univoci.",
                ["ProfileDevicesRequired"] = "“{0}” richiede un dispositivo di ingresso e uno di uscita.",
                ["UniqueShortcuts"] = "Le scorciatoie non possono essere assegnate più volte.",
                ["ToggleProfilesRequired"] = "La scorciatoia di cambio richiede due profili diversi.",
                ["ShortcutMissing"] = "Scorciatoia mancante.",
                ["InvalidKey"] = "Tasto non valido: {0}.",
                ["ShortcutKeyRequired"] = "La scorciatoia richiede un tasto.",
                ["ShortcutModifierRequired"] = "La scorciatoia richiede Ctrl, Alt, Maiusc o Win.",
                ["ShortcutCombinationRequired"] = "La scorciatoia richiede Ctrl, Alt, Maiusc o Win e un tasto.",
                ["ShortcutRegistrationTimeout"] = "La registrazione delle scorciatoie non ha risposto.",
                ["ShortcutAlreadyInUse"] = "La scorciatoia {0} è già in uso.",
                ["Open"] = "Apri",
                ["Exit"] = "Esci",
                ["UpdatePreparingFailed"] = "Impossibile preparare l’aggiornamento: {0}",
                ["UpdateCheckFailed"] = "Controllo aggiornamenti non riuscito: {0}",
                ["CheckingUpdates"] = "Controllo degli aggiornamenti…",
                ["UpToDate"] = "AudioSwitcher è aggiornato.",
                ["DownloadingUpdate"] = "Download dell’aggiornamento {0}…",
                ["DownloadProgress"] = "Download dell’aggiornamento: {0}%",
                ["UpdateOnExit"] = "L’aggiornamento {0} verrà installato all’uscita.",
                ["ProfileActivatedOverlay"] = "✓  Profilo “{0}” attivato",
            },
            ["pl"] = new Dictionary<string, string>
            {
                ["WindowsAudioRouting"] = "ROUTING DŹWIĘKU WINDOWS",
                ["RefreshDevices"] = "Odśwież urządzenia",
                ["RefreshDevicesTip"] = "Ponownie wczytaj dostępne urządzenia audio systemu Windows",
                ["Settings"] = "Ustawienia",
                ["About"] = "O programie",
                ["AboutDescription"] = "Profile audio Windows i globalne skróty klawiszowe. Autor: Diddlik.",
                ["CheckForUpdates"] = "Sprawdź aktualizacje",
                ["PackageCredits"] = "Autorzy pakietów",
                ["PackageCreditsHint"] = "Dziękujemy autorom zależności bezpośrednich i przechodnich, w tym narzędzi programistycznych. Szczegóły licencji znajdują się pod linkami do pakietów.",
                ["StandaloneUpdates"] = "Automatyczne aktualizacje wymagają zainstalowanej wersji. Dla tej samodzielnej kompilacji pobierz wydanie z GitHub.",
                ["ReleaseNotes"] = "Wydania i zmiany",
                ["SourceCode"] = "Kod źródłowy",
                ["Close"] = "Zamknij",
                ["System"] = "SYSTEM",
                ["Language"] = "Język",
                ["StartWithWindows"] = "Uruchamiaj z systemem Windows",
                ["CloseHint"] = "Zamknięcie ukrywa okno. Aby zakończyć, użyj menu w obszarze powiadomień.",
                ["Save"] = "Zapisz",
                ["UnsavedChanges"] = "Niezapisane zmiany",
                ["Profiles"] = "Profile",
                ["NoProfileSelected"] = "Nie wybrano profilu",
                ["NoProfileSelectedHint"] = "Dodaj profil, aby połączyć urządzenie wyjściowe z wejściowym.",
                ["AddProfile"] = "Dodaj profil",
                ["RemoveProfile"] = "Usuń profil",
                ["Profile"] = "PROFIL",
                ["DeviceCombination"] = "Kombinacja urządzeń",
                ["ActivateNow"] = "Aktywuj teraz",
                ["ActivateHelp"] = "Ustawia oba urządzenia jako domyślne w Windows dla odtwarzania, nagrywania i komunikacji.",
                ["ActivatedAt"] = "Aktywowano o {0}",
                ["NotActivatedThisSession"] = "Nieaktywowany w tej sesji",
                ["DeviceNotAvailable"] = "Urządzenie niedostępne",
                ["Name"] = "Nazwa profilu",
                ["NameExample"] = "np. Zestaw słuchawkowy",
                ["ProfileName"] = "Nazwa profilu",
                ["Output"] = "Urządzenie wyjściowe",
                ["Input"] = "Urządzenie wejściowe",
                ["OutputDevice"] = "Urządzenie wyjściowe",
                ["InputDevice"] = "Urządzenie wejściowe",
                ["ProfileShortcutLabel"] = "Globalny skrót dla tego profilu",
                ["ShortcutWatermark"] = "Kliknij tutaj i naciśnij skrót",
                ["ProfileShortcut"] = "Skrót profilu",
                ["ShortcutHelp"] = "Ustaw fokus w polu i naciśnij kombinację. Delete lub Backspace ją usuwa.",
                ["ShortcutHint"] = "Kliknij i naciśnij kombinację · Delete lub Backspace ją usuwa",
                ["QuickSwitch"] = "Szybkie przełączanie",
                ["QuickSwitchTitle"] = "Jeden skrót przełącza między dwoma profilami. AudioSwitcher sprawdza bieżące domyślne urządzenie wyjściowe i aktywuje drugi profil.",
                ["FirstToggleProfile"] = "Pierwszy profil",
                ["SecondToggleProfile"] = "Drugi profil",
                ["ToggleShortcut"] = "Skrót przełączania",
                ["LanguageHelp"] = "Interfejs zmienia się od razu. Zapisz, aby zachować wybór.",
                ["StartupHelp"] = "Otwiera się w zasobniku systemowym po zalogowaniu. Nie wymaga uprawnień administratora.",
                ["TrayTitle"] = "Zamykanie okna",
                ["TrayBody"] = "Po zamknięciu okna AudioSwitcher działa dalej w zasobniku systemowym, więc skróty i aktualizacje pozostają aktywne. Aby zakończyć, kliknij ikonę prawym przyciskiem i wybierz Zakończ.",
                ["Updates"] = "Aktualizacje",
                ["UpdatesBody"] = "Stabilne aktualizacje pobierają się automatycznie i instalują po zamknięciu AudioSwitcher.",
                ["Ready"] = "Gotowe",
                ["Version"] = "Wersja {0}",
                ["Unknown"] = "nieznana",
                ["DefaultProfile"] = "Profil {0}",
                ["ProfileCreated"] = "Utworzono nowy profil.",
                ["ProfileRemoved"] = "Usunięto profil. Zapisz, aby zastosować zmianę.",
                ["DeviceCounts"] = "Wyjścia: {0} · wejścia: {1}",
                ["ConfigurationSaved"] = "Zapisano konfigurację.",
                ["SaveFailed"] = "Nie udało się zapisać: {0}",
                ["SelectTwoProfiles"] = "Wybierz dwa profile do przełączania.",
                ["UnavailableDevice"] = "„{0}” wskazuje niedostępne urządzenie.",
                ["ProfileActive"] = "Profil {0} jest aktywny.",
                ["ProfileActivationFailed"] = "Nie udało się aktywować profilu: {0}",
                ["ProfileRequired"] = "Wymagany jest co najmniej jeden profil.",
                ["ProfileNameRequired"] = "Każdy profil musi mieć nazwę.",
                ["UniqueProfileNames"] = "Nazwy profili muszą być unikatowe.",
                ["ProfileDevicesRequired"] = "„{0}” wymaga urządzenia wejściowego i wyjściowego.",
                ["UniqueShortcuts"] = "Skrótów nie można przypisać więcej niż raz.",
                ["ToggleProfilesRequired"] = "Skrót przełączania wymaga dwóch różnych profili.",
                ["ShortcutMissing"] = "Brak skrótu.",
                ["InvalidKey"] = "Nieprawidłowy klawisz: {0}.",
                ["ShortcutKeyRequired"] = "Skrót wymaga klawisza.",
                ["ShortcutModifierRequired"] = "Skrót wymaga Ctrl, Alt, Shift lub Win.",
                ["ShortcutCombinationRequired"] = "Skrót wymaga Ctrl, Alt, Shift lub Win oraz klawisza.",
                ["ShortcutRegistrationTimeout"] = "Rejestracja skrótów nie odpowiedziała.",
                ["ShortcutAlreadyInUse"] = "Skrót {0} jest już używany.",
                ["Open"] = "Otwórz",
                ["Exit"] = "Zakończ",
                ["UpdatePreparingFailed"] = "Nie udało się przygotować aktualizacji: {0}",
                ["UpdateCheckFailed"] = "Nie udało się sprawdzić aktualizacji: {0}",
                ["CheckingUpdates"] = "Sprawdzanie aktualizacji…",
                ["UpToDate"] = "AudioSwitcher jest aktualny.",
                ["DownloadingUpdate"] = "Pobieranie aktualizacji {0}…",
                ["DownloadProgress"] = "Pobieranie aktualizacji: {0}%",
                ["UpdateOnExit"] = "Aktualizacja {0} zostanie zainstalowana przy zamknięciu.",
                ["ProfileActivatedOverlay"] = "✓  Aktywowano profil „{0}”",
            },
        };

    private string _currentLanguage = DefaultLanguage;
    private IReadOnlyDictionary<string, string> _strings = Translations[DefaultLanguage];

    static LocalizationService()
    {
        var requiredKeys = Translations[DefaultLanguage].Keys.ToHashSet(StringComparer.Ordinal);
        foreach (var translation in Translations.Values)
        {
            if (!requiredKeys.SetEquals(translation.Keys))
            {
                throw new InvalidOperationException("Every language must contain the same translation keys.");
            }
        }
    }

    public event EventHandler? LanguageChanged;

    public IReadOnlyList<LanguageOption> SupportedLanguages => Languages;
    public string CurrentLanguage => _currentLanguage;
    public string this[string key] => _strings.TryGetValue(key, out var value) ? value : Translations[DefaultLanguage][key];

    public void SetLanguage(string? languageCode)
    {
        var code = Languages.FirstOrDefault(language =>
            string.Equals(language.Code, languageCode, StringComparison.OrdinalIgnoreCase))?.Code ?? DefaultLanguage;
        if (string.Equals(_currentLanguage, code, StringComparison.OrdinalIgnoreCase)) return;

        _currentLanguage = code;
        _strings = Translations[code];
        var culture = CultureInfo.GetCultureInfo(code);
        CultureInfo.CurrentUICulture = culture;
        CultureInfo.DefaultThreadCurrentUICulture = culture;
        OnPropertyChanged("Item");
        OnPropertyChanged(nameof(CurrentLanguage));
        LanguageChanged?.Invoke(this, EventArgs.Empty);
    }

    public string Format(string key, params object?[] arguments) =>
        string.Format(CultureInfo.CurrentCulture, this[key], arguments);
}
